version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: duitku_pgsql
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pg_data:

networks:
  app-network:
    name: app-network
    driver: bridge
